#!/bin/bash
sed -i '' 's/border-grayscale-12 bg-\[color-mix[^]]*\]/border-ink-900 bg-[#2C2C2C]/g' src/components/ui/receipt-printer.tsx
sed -i '' 's/shadow-\[0_20px_36px_-20px_color-mix[^]]*\]/shadow-[0_20px_36px_-20px_rgba(0,0,0,0.55),0_6px_14px_-8px_rgba(0,0,0,0.24),inset_0_1px_0_rgba(255,255,255,0.14),inset_0_-1px_0_rgba(0,0,0,0.55)]/g' src/components/ui/receipt-printer.tsx
sed -i '' 's/dark:border-grayscale-3 dark:bg-grayscale-4 dark:shadow-\[0_20px_36px_-20px_color-mix[^]]*\]/dark:border-ink-600 dark:bg-ink-700 dark:shadow-[0_20px_36px_-20px_rgba(0,0,0,0.55)]/g' src/components/ui/receipt-printer.tsx
sed -i '' 's/border-grayscale-12 bg-grayscale-12 shadow-inner shadow-grayscale-12 dark:border-grayscale-1 dark:bg-white dark:shadow-grayscale-1/border-black bg-black shadow-inner shadow-black dark:border-ink-100 dark:bg-white dark:shadow-ink-100/g' src/components/ui/receipt-printer.tsx
sed -i '' 's/border-grayscale-12 bg-grayscale-12 p-4 text-grayscale-1 shadow-inner shadow-grayscale-12\/80 after:pointer-events-none after:absolute after:inset-0 after:z-20 after:rounded-\[inherit\] after:shadow-\[inset_0_0_24px_4px_color-mix(in_oklab,var(--color-grayscale-12)_52%,transparent)\] after:content-\['\''\''\] dark:border-grayscale-1 dark:bg-grayscale-2 dark:text-grayscale-12 dark:shadow-grayscale-1\/80 dark:after:shadow-\[inset_0_0_24px_4px_color-mix(in_oklab,var(--color-grayscale-1)_52%,transparent)\]/border-black bg-[#1E1E1E] p-4 text-white shadow-inner shadow-black\/80 after:pointer-events-none after:absolute after:inset-0 after:z-20 after:rounded-[inherit] after:shadow-[inset_0_0_24px_4px_rgba(0,0,0,0.52)] after:content-['\'\''\'\''] dark:border-white dark:bg-ink-50 dark:text-ink-900 dark:shadow-white\/80 dark:after:shadow-[inset_0_0_24px_4px_rgba(255,255,255,0.52)]/g' src/components/ui/receipt-printer.tsx
sed -i '' 's/text-grayscale-8 dark:text-grayscale-11/text-ink-400 dark:text-ink-500/g' src/components/ui/receipt-printer.tsx
sed -i '' 's/text-grayscale-8 text-xs leading-none dark:text-grayscale-11/text-ink-300 text-xs leading-none dark:text-ink-600/g' src/components/ui/receipt-printer.tsx
sed -i '' 's/bg-grayscale-12\/75 blur-\[6px\] dark:bg-grayscale-1\/75/bg-black\/75 blur-[6px] dark:bg-white\/75/g' src/components/ui/receipt-printer.tsx
sed -i '' 's/before:shadow-\[0_8px_24px_color-mix(in_oklab,var(--color-grayscale-12)_24%,transparent)\] before:content-\['\''\''\] after:pointer-events-none after:absolute after:right-\[8%\] after:bottom-0 after:left-\[8%\] after:z-0 after:h-3 after:translate-y-1.5 after:rounded-full after:bg-grayscale-12\/10 after:blur-lg after:content-\['\''\''\] dark:before:shadow-\[0_8px_24px_color-mix(in_oklab,var(--color-grayscale-1)_20%,transparent)\] dark:after:bg-grayscale-1\/10/before:shadow-[0_8px_24px_rgba(0,0,0,0.24)] before:content-['\'\''\'\''] after:pointer-events-none after:absolute after:right-[8%] after:bottom-0 after:left-[8%] after:z-0 after:h-3 after:translate-y-1.5 after:rounded-full after:bg-black\/10 after:blur-lg after:content-['\'\''\'\''] dark:before:shadow-[0_8px_24px_rgba(255,255,255,0.2)] dark:after:bg-white\/10/g' src/components/ui/receipt-printer.tsx

